runconfig:
    PGENameGroup:
      PGEName: "L0B_L_PGE"
    InputFilePath: 
      L0A_L_RRST: "__CHIMERA_VAL__"
    DynamicAncillaryFileGroup:
      RadarConfigurationFile: "__CHIMERA_VAL__"
      ChirpParameterFile: "__CHIMERA_VAL__"
      WaveformConfigurationFile: "__CHIMERA_VAL__"
      LRCLKFile: "__CHIMERA_VAL__"
    ProductPathGroup:
      ProductPath: "output"
      ProductCounter: "__CHIMERA_VAL__"
    PrimaryExecutable:
      CompositeReleaseID: "__CHIMERA_VAL__"
      ProcessingType: "__CHIMERA_VAL__"
      MissionId: "NISAR"
      ProductType: "__CHIMERA_VAL__"
      RadarProcessingMode: "__CHIMERA_VAL__"
      NumberOfThreads: 90
    DebugLevelGroup:
      DebugSwitch: "__CHIMERA_VAL__"
    TimeOffset: "__CHIMERA_VAL__"
    MakeHstDrtFile: "__CHIMERA_VAL__"
    PlannedDatatakeId: "__CHIMERA_VAL__"
    DatatakeStartDateTime: "__CHIMERA_VAL__"
    DatatakeStopDateTime: "__CHIMERA_VAL__"

    # Under the Observations area, it can have one or more Observation
    # - Observation:
    #  PlannedObservationId
    #  StartTime
    #  EndTime
    #  IsUrgentObservation
    #  ConfigurationId
    #  MissionCycle
    #  TotalNumberRangelines
    #  RangelinesToSkip
    Observations: "__CHIMERA_VAL__"
    Geometry:
      AbsoluteOrbitNumber: "__CHIMERA_VAL__"
      RelativeOrbitNumber: "__CHIMERA_VAL__"
      OrbitDirection: "__CHIMERA_VAL__"
      LookDirection: "__CHIMERA_VAL__"
    pge_job_name: "__CHIMERA_VAL__"
    mock_metadata: "__CHIMERA_VAL__"
    base_name: "__CHIMERA_VAL__"
    extra_pge_output_metadata: "__CHIMERA_VAL__"

preconditions:
  - get_crid
  - get_products
  - get_metadata
  - get_product_metadata
  - get_range_date_times
  - get_processing_type
  - get_metadata
  - get_hardcoded_metadata
  - get_l0b_ancillary_files
  - get_product_most_recent_version
  - get_observations_data
  - get_stuf_info
  - get_pge_settings_values
# - get_number_of_threads_doubled
  - get_product_counter
  - set_product_time
  - set_pge_job_name
  - set_l0b_mock_metadata
  - set_l0b_base_names
  - set_extra_pge_output_metadata

# This lists all the postprocessor steps that this PGE will run after running the PGE.
postprocess:
  - update_observation_product_accountability

get_products:
  is_state_config_trigger: true
  file_names_key: "found_l0a_rrsts"

get_metadata:
  keys:
    - input_dataset_id

get_product_metadata:
  keys:
    - datatake_id
    - datatake_begin_time
    - datatake_end_time
    - observation_begin_time
    - observation_end_time
    - observation_ids
    - is_urgent
  attribute_names:
    datatake_id: PlannedDatatakeId
    datatake_begin_time: DatatakeStartDateTime
    datatake_end_time: DatatakeStopDateTime

get_processing_type:

#Some metadata values are hardcoded now. Putting them in pge_params to be used other places
get_hardcoded_metadata:
    MissionCycle: "001"
    RadarProcessingMode: "S"
    ProductType: "RRSD"
    DebugSwitch: "Off"
    TimeOffset: 0

get_product_most_recent_version:
  types:
    - SCLKSCET
  filters:
    SCLKSCET:
      metadata.Type: "LRCLK"
  attribute_names:
    SCLKSCET: "LRCLKFile"

get_observations_data:
  beginning_date_time: "RangeStartDateTime"
  ending_date_time: "RangeStopDateTime"

# This will look at PGE specific settings set in the settings.yaml and map it to a specified value,
# which is expected to go into the RunConfig
get_pge_settings_values:
  MAKE_HST_DRT_FILE: MakeHstDrtFile

get_product_counter:
    metadata.datatake_state_config_id.keyword: "input_dataset_id"
    metadata.CompositeReleaseID.keyword: "CompositeReleaseID"
    metadata.ProcessingType.keyword: "ProcessingType"

# This value will get used as part of the job id during the job submission step.
set_pge_job_name:
  template: "{input_dataset_id}"

set_l0b_base_names:
  L0B_L_RRSD:
    template: NISAR_L0_{ProcessingType}_RRSD_001_001_D_{RadarMode}S_{RangeStartDateTime}_{RangeStopDateTime}_{CompositeReleaseID}_M_{ProductCounter:03d}
    date_time_formats:
      RangeStartDateTime: "%Y%m%dT%H%M%S"
      RangeStopDateTime: "%Y%m%dT%H%M%S"
  L0B_L_CRSD:
    template: NISAR_L0_{ProcessingType}_CRSD_001_001_D_{RangeStartDateTime}_{RangeStopDateTime}_{CompositeReleaseID}_{ProductCounter:03d}
    date_time_formats:
      RangeStartDateTime: "%Y%m%dT%H%M%S"
      RangeStopDateTime: "%Y%m%dT%H%M%S"
  L0B_L_HST_DRT:
    template: NISAR_L0_{ProcessingType}_HST_DRT_001_001_D_{RangeStartDateTime}_{RangeStopDateTime}_{CompositeReleaseID}_{ProductCounter:03d}
    date_time_formats:
      RangeStartDateTime: "%Y%m%dT%H%M%S"
      RangeStopDateTime: "%Y%m%dT%H%M%S"

set_l0b_mock_metadata:
  L0B_L_RRSD:
    static:
      PGE_Name: "L0B_L_PGE"
      PGE_Version: "R1.1.0"
      SAS_Version: "ISCE3 v0.2.0-dev"
      TotalNumberOfMissingRangelines: 10
      TotalNumberOfRangelinesFailedChecksum: 1
      TotalNumberRangelines: 99999

    dynamic:
      Input_Files: L0A_L_RRST
      Ancillary_Files:
        - RadarConfigurationFile
        - ChirpParameterFile
        - WaveformConfigurationFile
        - LRCLKFile
      Production_DateTime: ProductionDateTime
      CompositeReleaseID: CompositeReleaseID
      ProductCounter: ProductCounter
      ProcessingType: ProcessingType

    observations:
      OBS_ID: PlannedObservationId
      RadarMode: ConfigurationId
      RangeStartDateTime: StartTime
      ObservationStartDateTime: StartTime
      RangeStopDateTime: EndTime
      ObservationEndDateTime: EndTime

  L0B_L_CRSD:
    static:
      PGE_Name: "L0B_L_PGE"
      PGE_Version: "V1.0"
      TotalNumberOfMissingRangelines: 10
      TotalNumberOfRangelinesFailedChecksum: 1
      DATATAKE_ID: "2020-10-02T02:48:30"
      TotalNumberRangelines: 99999

    dynamic:
      Input_Files: L0A_L_RRST
      Ancillary_Files:
        - RadarConfigurationFile
        - ChirpParameterFile
        - WaveformConfigurationFile
        - LRCLKFile
      Production_DateTime: ProductionDateTime
      RangeStartDateTime: DatatakeStartDateTime
      RangeStopDateTime: DatatakeStopDateTime
      CompositeReleaseID: CompositeReleaseID
      ProductCounter: ProductCounter
      DatatakeStartDateTime: DatatakeStartDateTime
      DatatakeStopDateTime: DatatakeStopDateTime
      ProcessingType: ProcessingType

  L0B_L_HST_DRT:
    static:
      PGE_Name: "L0B_L_PGE"
      PGE_Version: "V1.0"
      TotalNumberOfMissingRangelines: 10
      Total_NumberOfRangelinesFailedChecksum: 1
      DATATAKE_ID: "2020-10-02T02:48:30"
      TotalNumberRangelines: 99999

    dynamic:
      Input_Files: L0A_L_RRST
      Ancillary_Files:
        - RadarConfigurationFile
        - ChirpParameterFile
        - WaveformConfigurationFile
        - LRCLKFile
      Production_DateTime: ProductionDateTime
      RangeStartDateTime: DatatakeStartDateTime
      RangeStopDateTime: DatatakeStopDateTime
      CompositeReleaseID: CompositeReleaseID
      ProductCounter: ProductCounter
      DatatakeStartDateTime: DatatakeStartDateTime
      DatatakeStopDateTime: DatatakeStopDateTime
      ProcessingType: ProcessingType

# This function will add to the PGE output metadata when product to dataset conversion is performed
set_extra_pge_output_metadata:
  datatake_state_config_id: input_dataset_id
  DatatakeStartDateTime: DatatakeStartDateTime
  DatatakeStopDateTime: DatatakeStopDateTime
  IsUrgent: is_urgent_response

output_types:
  L0B_L_RRSD:
    - h5
    - h5.log
    - h5.met
  L0B_L_CRSD:
    - h5
    - h5.met
  L0B_L_HST_DRT:
    - bin
    - bin.met

pge_name: "L0B"

# Set the primary input/output types here
primary_input: "L0A_L_RRST"
primary_output: "L0B_L_RRSD"

localize_groups:
  - InputFilePath
  - DynamicAncillaryFileGroup
