# The runconfig section is intended to be used for dynamically generating the runconfig file used
# when running the OPERA PGEs. Any values set with a "__CHIMERA_VAL__" should be filled in by the input
# preprocessor. Otherwise, a precondition evaluation error will be thrown.
runconfig:
  name: dswx_hls_workflow_default
  pge_name_group:
    pge_name: DSWX_HLS_PGE
  input_file_group:
    # REQUIRED - Single HLS dataset (directory or files)
    input_file_path: [input_dir]
  dynamic_ancillary_file_group:
    # Digital elevation model
    dem_file:
    # Copernicus Land Cover Layer (CLCL)
    landcover_file:
    # Copernicus Human Settlement Layer (GHSL)
    built_up_cover_fraction_file:
  product_path_group:
    # Directory where PGE will place results
    product_path: product_path
    # Directory where SAS can write temporary data
    scratch_path: scratch_dir
    # Intermediate file name.  SAS writes output product to the following file.
    # After the SAS completes, the PGE wrapper renames the product file
    # according to proper file naming conventions.
    sas_output_file: output_dir/dswx_hls.tif
  primary_executable:
      product_type: DSWX_HLS

  # TODO chrisjrd: replace hardcoded value. support PGE simulation mode toggle
  # Needed for an implicit simulated PGE run.
  # * See PGE_SIMULATION_MODE in settings.yaml and it's usage
  # * See SIMULATE_OUTPUTS usage in opera_pge_wrapper.py and chimera.precondition_evaluator.py
  base_name:
    L3_DSWx: OPERA_L3_DSWx_HLS_Sentinel2_T15SXR_20210211T163901_01
  mock_metadata:
    L3_DSWx: {dummy_key: dummy_value}

# This lists all the precondition evaluation steps that this PGE needs to run prior to running the PGE.
preconditions: []

# This lists all the postprocessor steps that this PGE will run after running the PGE.
postprocess: []

# For any of the precondition evaluation steps listed in the preconditions area,
# specify function arguments here

# List the extensions that the PGE generates
output_types:
  L3_DSWx:
    - tiff
    - log
    - met
    - qa
    - xml

# The PGE name
pge_name: "L2_HLS"

# Set the primary input/output types here
primary_input: "L2_HLS_L30"
primary_output: "L3_DSWx"

# List the groups that Chimera will need to localize
localize_groups: []
