#######################################################################
# PGE configuration for L3_HLS.
#######################################################################

# The runconfig section is intended to be used for dynamically generating the runconfig file used
# when running the OPERA PGEs. Any values set with a "__CHIMERA_VAL__" should be filled in by the input
# preprocessor. Otherwise, a precondition evaluation error will be raised by chimera.
#
# The runconfig section is also used as the data dict for the RunConfig jinja2 template.
# Accordingly, the schema here does NOT need to match the final RunConfig.yaml schema.
#
# * See RunConfig_schema.<label>.yaml for RunConfig.yaml documentation.
# * See related `RunConfig.yaml.<label>.jinja2.tmpl` file
#  and `util.conf_util.RunConfig.__init__()` for jinja2 usage.
runconfig:
  input_file_group:
    input_file_path: []
  dynamic_ancillary_file_group:
    dem_file:  # Digital elevation model
    landcover_file:  # Copernicus Land Cover Layer (CLCL)
    built_up_cover_fraction_file:  # Copernicus Human Settlement Layer (GHSL)
  product_path_group:
    product_path: output_dir
    scratch_path: scratch_dir
    sas_output_file: dswx_hls.tif

  product_paths:
    # references an output dict entry of a precondition function to pass remote product URL onto localization phase.
    L2_HLS: __CHIMERA_VAL__

# This lists all the precondition evaluation steps that this PGE needs to run prior to running the PGE.
preconditions: [get_input_filepaths_from_state_config]

# This lists all the postprocessor steps that this PGE will run after running the PGE.
postprocess: []

# For any of the precondition evaluation steps listed in the preconditions area,
# specify function arguments here

# List the extensions that the PGE generates
output_types:
  L3_DSWx:
    - tif
    - met
    - log

# The PGE name
# This must MATCH the corresponding entry in pge_outputs.yaml
pge_name: "L3_HLS"

# Set the primary input/output types here
primary_input: "L2_HLS_L30"
primary_output: "L3_DSWx"

# List the groups that Chimera will need to localize
# The entries MUST reference a property of `$.runconfig` of this YAML.
# The referenced properties MUST be maps.
localize_groups: [product_paths]


#######################################################################
# PGE Simulation Mode
#
# * See PGE_SIMULATION_MODE in settings.yaml and it's usage
# * See SIMULATE_OUTPUTS usage in opera_pge_wrapper.py and chimera.precondition_evaluator.py
#######################################################################
input_file_base_name_regexes: # regexes taken from settings.yaml > L2_HLS_L30 and L2_HLS_S30
    - '(?P<id>(?P<product_shortname>HLS[.]L30)[.](?P<tile_id>T[^\W_]{5})[.](?P<acquisition_ts>(?P<year>\d{4})(?P<day_of_year>\d{3})T(?P<hour>\d{2})(?P<minute>\d{2})(?P<second>\d{2}))[.](?P<collection_version>v\d+[.]\d+)_state_config)$'
    - '(?P<id>(?P<product_shortname>HLS[.]S30)[.](?P<tile_id>T[^\W_]{5})[.](?P<acquisition_ts>(?P<year>\d{4})(?P<day_of_year>\d{3})T(?P<hour>\d{2})(?P<minute>\d{2})(?P<second>\d{2}))[.](?P<collection_version>v\d+[.]\d+)_state_config)$'
output_base_name: OPERA_L3_DSWx_HLS_{sensor}_{tile_id}_{datetime}_{collection_version}
