runconfig:
  name: NISAR_GCOV_RUNCONFIG
  PGENameGroup:
    PGEName: "GCOV_L_PGE"
  InputFilePath:
    L1_L_RSLC: "__CHIMERA_VAL__"
  DynamicAncillaryFileGroup:
    DEMFile: "__CHIMERA_VAL__"
  PrimaryExecutable:
    ProductType: GCOV
    CompositeReleaseID: "__CHIMERA_VAL__"
    ProductAccuracy: "__CHIMERA_VAL__"
  ProductPathGroup:
    # Directory where PGE will place results. Irrelevant to SAS.
    ProductPath: "output"
    # Directory where SAS can write temporary data
    ScratchPath: "scratch"
    # SAS writes output product to the following file. PGE may rename.
    # NOTE: For R2 will need to handle mixed-mode case with multiple outputs of RSLC workflow.
    SASOutputFile: "output/gcov.h5"
    ProductCounter: "__CHIMERA_VAL__"
  DebugLevelGroup:
    DebugSwitch: Off
      #adt section - isce3 + pyre workflow
  processing:
    input_subset:           # {optional} Mechanism to select frequencies and polarizations
      list_of_frequencies:  # {optional} List of frequencies to process. Default empty representing all
        A:                  # {optional} List of polarization channels to process. Default empty representing all
        #B:
      fullcovariance: "__CHIMERA_VAL__"  # {optional} Compute cross-elements (True) or diagonals only (False). Default: False

    dem_download:   # {optional} Only checked when internet access is available
      source: None  # {optional} s3 bucket / curl URL / local file
      top_left:
        x:
        y:
      bottom_right:
        x:
        y:

    pre_process:        # {optional} Pre-processing options (before geocoding)
      azimuth_looks: 1  # {optional} Number of looks in azimuth
      range_looks: 1    # {optional} Number of looks in range

    rtc:                                # {optional} RTC options
      output_type: "__CHIMERA_VAL__"                 # {optional} Choices: “None” (to turn off RTC) or “gamma0”
      algorithm_type: "__CHIMERA_VAL__"              # {optional} Choices: "area_projection" (default) and "bilinear_distribution"
      input_terrain_radiometry: sigma0   # {optional} Choices: "beta0" and "sigma0"
      rtc_min_value_db: -30             # {optional} Minimum RTC area factor in dB

    geocode:                           # {optional} Mechanism to specify output posting and DEM
      algorithm_type: area_projection  # {optional} Choices: "area_projection" (default) and "interp"
      memory_mode:                    # {optional} Choices: "auto", "single-block" "blocks-geogrid", and "blocks-geogrid-and-radargrid"
      geogrid_upsampling: 1      # {optional} Processing upsampling factor on top of the input geogrid
      save_nlooks: True          # {optional} Save the number of looks used to compute GCOV
      save_rtc: True             # {optional} Save the RTC area factor used to compute GCOV
      abs_rad_cal: 1 # {optional} Absolute radiometric correction factor
      outputEPSG:                # {optional} Same as input DEM if not provided.
      output_posting:
        A:
          x_posting:
          y_posting:
        B:
          x_posting:
          y_posting:
      x_snap:        # {optional} To control output grid in same units as output EPSG
      y_snap:        # {optional} To control output grid in same units as output EPSG
      top_left:      # {optional} Can control with absolute values or with snap values
        y_abs:       # {optional} Set top-left y in same units as output EPSG
        x_abs:       # {optional} Set top-left x in same units as output EPSG
      bottom_right:  # {optional} Can control with absolute values or with snap values
        y_abs:
        x_abs:
    # not supported in R1.1 PGE
    #geo2rdr:
    #  threshold:
    #  maxiter:
    noise_correction:         # {optional} If noise correction desired (for ISRO)
      apply_correction: False # {optional}
      correction_type:  # {optional}

  worker:                          # {optional} To setup type of worker
    internet_access: False         # {optional} To prevent downloading DEM / other data automatically. Default True
    gpu_enabled: "__CHIMERA_VAL__" # {optional} To explicitly use GPU capability if available. Default False

  QA:
    validate: True
    quality: True
  pge_job_name: "__CHIMERA_VAL__"
  mock_metadata: "__CHIMERA_VAL__"
  base_name: "__CHIMERA_VAL__"

preconditions:
  - get_gpu_enabled
  - get_crid
  - get_products
  - get_metadata
  - get_product_metadata
  - get_gcov_job_params_from_context
  - get_hardcoded_metadata
  - set_pcm_retrieval_id
  - get_product_counter
  - get_dems
  - set_product_time
  - set_pge_job_name
  - set_mock_metadata
  - set_base_name

postprocess:
  - update_track_frame_product_accountability

get_dems:
  # Can take bbox as before or product metadata key containing the GeoJSON polygon
  #bbox: "-122.121 36.321 -121.84 36.556"
  polygon_key: BOUNDING_POLYGON

get_metadata:
  keys:
    - input_dataset_id

get_gcov_job_params_from_context:
  keys:
    - fullcovariance
    - output_type
    - algorithm_type
    - output_posting

# Looks at the metadata area under the product_metadata area in the context
get_product_metadata:
  keys:
    - RadarStartDateTime
    - RadarStopDateTime
    - CycleNumber
    - RelativeOrbitNumber
    - TrackFrame
    - Bounding_Polygon
    - ProcessingType
  attribute_names:
    TrackFrame: FrameNumber

get_hardcoded_metadata:
  ProductAccuracy: P
  OrbitDirection: Descending
  OrbitDirectionLetter: D

get_product_counter:
  metadata.PCMRetrievalID.keyword: "PCMRetrievalID"
  metadata.CompositeReleaseID.keyword: "CompositeReleaseID"

set_pge_job_name:
  template: "{input_dataset_id}"

set_mock_metadata:
  # Hard-coded values in the structure you want
  L2_L_GCOV:
    static:
      PGE_Name: "GCOV_L_PGE"
      PGE_Version: "R1.1.0"
      SAS_Version: "ISCE3 v0.2.0-dev"
    dynamic:
      Input_Files: L1_L_RSLC
      Production_DateTime: ProductionDateTime
      RadarStartDateTime: RadarStartDateTime
      RadarStopDateTime: RadarStopDateTime
      CompositeReleaseID: CompositeReleaseID
      Bounding_Polygon: Bounding_Polygon
      ProcessingType: ProcessingType
      CycleNumber: CycleNumber
      RelativeOrbitNumber: RelativeOrbitNumber
      OrbitDirection: OrbitDirection
      OrbitDirectionLetter: OrbitDirectionLetter
      FrameNumber: FrameNumber
      ProductAccuracy: ProductAccuracy
      ProductCounter: ProductCounter

# When performing simulated PGE runs, this sets the base name to be used when generating the output
# products.
set_base_name:
  L2_L_GCOV:
    template: NISAR_L2_{ProcessingType}_GCOV_{CycleNumber:03d}_{RelativeOrbitNumber:03d}_{OrbitDirectionLetter}_{FrameNumber:03d}_4020_VV_{RadarStartDateTime}_{RadarStopDateTime}_{CompositeReleaseID}_{ProductAccuracy}_F_{ProductCounter:03d}
    date_time_formats:
      RadarStartDateTime: "%Y%m%dT%H%M%S"
      RadarStopDateTime: "%Y%m%dT%H%M%S"

# Creates the PCMRetrievalID value to determine product counter
set_pcm_retrieval_id:
  template: NISAR_L2_{ProcessingType}_GCOV_{CycleNumber}_{RelativeOrbitNumber}_{OrbitDirectionLetter}_{FrameNumber}_{ProductAccuracy}

# The PGE name
pge_name: "GCOV"

# Set the primary input/output types here
primary_input: "L1_L_RSLC"
primary_output: "L2_L_GCOV"

# List the extensions that the PGE generates
output_types:
  L2_L_GCOV:
    - h5
    - h5.log
    - h5.met

# List the groups that Chimera wil l need to localize
localize_groups:
  - InputFilePath
  - DynamicAncillaryFileGroup
