# Copyright 2019-2020, by the California Institute of Technology.
# ALL RIGHTS RESERVED.
# United States Government sponsorship acknowledged.
# Any commercial use must be negotiated with the Office of Technology Transfer
# at the California Institute of Technology.
# This software may be subject to U.S. export control laws and regulations.
# By accepting this document, the user agrees to comply with all applicable
# U.S. export laws and regulations. User has the responsibility to obtain
# export licenses, or other export authority as may be required, before
# exporting such information to foreign countries or providing access to
# foreign persons.
#
# This is a Yamale schema (see https://github.com/23andMe/Yamale) for
# validating run config files for the NISAR LSAR time extractor PGE.
#
runconfig:
  name: str()
  groups:
    PGENameGroup:
      PGEName: enum('LSAR_TIME_EXTRACTOR_PGE', 'NISAR_LSAR_EX_RUNCONFIG')
    InputFileGroup:
      InputFilePath: list(str(), min=1)
    DynamicAncillaryFileGroup:
      LRCLKFile: str()
    ProductPathGroup:
      ProductPath: str()
    DebugLevelGroup:
      DebugSwitch: bool()
