# This is a Yamale schema (see https://github.com/23andMe/Yamale) for
# validating run config files for the OPERA level 3 PGE.
#
runconfig:
  name: enum('dswx_hls_workflow_default')
  groups:
    pge_name_group:
      pge_name: enum('DSWX_HLS_PGE')
    input_file_group:
      input_file_path: list(str(), min=1)
    dynamic_ancillary_file_group:
      dem_file: str(required=False)
      landcover_file: str(required=False)
      built_up_cover_fraction_file: str(required=False)
    product_path_group:
      product_path: str()
      scratch_path: str()
      sas_output_file: str()
    primary_executable:
      product_type: enum('DSWX_HLS')
